allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  supabase: true
  vue-demi: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - sharp
  - supabase
  - vue-demi
